// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdENHetyyL4ycnnNE9L2uIHB8vYNADrY',
    appId: '1:478171997531:web:bd9b10354fd98d6c8e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    authDomain: 'spendly-d2750.firebaseapp.com',
    storageBucket: 'spendly-d2750.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdENHetyyL4ycnnNE9L2uIHB8vYNADrY',
    appId: '1:478171997531:android:35104b2f3ebdb5068e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8ZlGAP234Wss7pqIQWQZGLHsOVx62Fg',
    appId: '1:478171997531:ios:e2cfd4619b3feea78e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
    iosBundleId: 'com.spendly.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD8ZlGAP234Wss7pqIQWQZGLHsOVx62Fg',
    appId: '1:478171997531:ios:e2cfd4619b3feea78e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
    iosBundleId: 'com.spendly.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZdENHetyyL4ycnnNE9L2uIHB8vYNADrY',
    appId: '1:478171997531:android:35104b2f3ebdb5068e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDZdENHetyyL4ycnnNE9L2uIHB8vYNADrY',
    appId: '1:478171997531:android:35104b2f3ebdb5068e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
  );
}
