// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5aImC0sUfZOUot5EGZhGX4EUaDIU3DI',
    appId: '1:478171997531:web:bd9b10354fd98d6c8e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    authDomain: 'spendly-d2750.firebaseapp.com',
    storageBucket: 'spendly-d2750.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdENHetyyL4ycnnNE9L2uIHB8vYNADrY',
    appId: '1:478171997531:android:35104b2f3ebdb5068e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8ZlGAP234Wss7pqIQWQZGLHsOVx62Fg',
    appId: '1:478171997531:ios:e2cfd4619b3feea78e267e',
    messagingSenderId: '478171997531',
    projectId: 'spendly-d2750',
    storageBucket: 'spendly-d2750.firebasestorage.app',
    iosBundleId: 'com.spendly.expensetracker',
  );
}
